apiVersion: v1
kind: Service
metadata:
  name: live-conversation-web-app-service
  labels:
    app.kubernetes.io/name: web-app-service
    app.kubernetes.io/part-of: live-conversation
spec:
  selector:
    app: live-conversation-web-app
  ports:
  - name: live-conversation-web-app-service
    port: 8000
    targetPort: 8000
    protocol: TCP
