apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qa
resources:  
 - ../../base
patchesStrategicMerge:
  - "patches.yaml"

patches:
  - target:
      kind: Ingress
      name: live-conversation-web-app
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: live-qa.labmojodoo.com