apiVersion: apps/v1
kind: Deployment
metadata:
  # name: live-conversation-web-app-deployment
  name: live-conversation-web-app
  labels:
    # app.kubernetes.io/name: live-conversation-web-app-deployment
    app.kubernetes.io/name: live-conversation-web-app
spec:
 selector:
    matchLabels:
      app: live-conversation-web-app
 replicas: 1
 template:
   spec:
     containers:
       - name: live-conversation-web-app
         env: 
           - name: myVar
             value: myVarValue

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  # name: live-conversation-web-app-ingress
  name: live-conversation-web-app
spec:
  rules:
  - host: live-qa.labmojodoo.com
              
---