apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml

# Base-kustomization of below properties (=for ALL images)
images:
  - name: crdevwe001.azurecr.io/live-conversation/web-app
    # Add tag to ALL images - tag-value defined in pipeline
    newTag: $IMAGE_TAG
