apiVersion: apps/v1
kind: Deployment
metadata:
  name: live-conversation-web-app-deployment
  labels:
    app.kubernetes.io/name: web-app-deployment
    app.kubernetes.io/part-of: live-conversation
spec:
 template:
   spec:
     containers:
       - name: live-conversation-web-app
         env: 
           - name: myVar
             value: myVarValue

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: live-conversation-web-app-ingress
spec:
  rules:
  - host: live-dev.labmojodoo.com
  
---